"""games and reviews

Revision ID: 0001
Revises: 
Create Date: 2026-09-24 19:04:35.861615

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('appid', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('last_ingested_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('appid')
    )
    op.create_table('reviews',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('appid', sa.Integer(), nullable=False),
    sa.Column('review_text', sa.Text(), nullable=False),
    sa.Column('voted_up', sa.Boolean(), nullable=False),
    sa.Column('votes_up', sa.Integer(), nullable=False),
    sa.Column('playtime_forever', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['appid'], ['games.appid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_appid'), 'reviews', ['appid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_appid'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_table('games')
    # ### end Alembic commands ###
