"""review aspects

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-24 22:41:35.807722

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: str | Sequence[str] | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_aspects',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('review_id', sa.BigInteger(), nullable=False),
    sa.Column('sentence_text', sa.Text(), nullable=False),
    sa.Column('aspect_label', sa.String(length=16), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=False),
    sa.Column('predicted_sentiment', sa.String(length=8), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_aspects_review_id'), 'review_aspects', ['review_id'], unique=False)
    op.add_column('games', sa.Column('aspects_processed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'aspects_processed_at')
    op.drop_index(op.f('ix_review_aspects_review_id'), table_name='review_aspects')
    op.drop_table('review_aspects')
    # ### end Alembic commands ###
